docker-build:
  image: jdrouet/docker-with-buildx:stable
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker context create $CI_JOB_ID
    - docker buildx create $CI_JOB_ID --name multiarch --driver docker-container --use
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag $CI_REGISTRY_IMAGE .
  only:
    - master
